title: robot-plus-program
lang: kr
description: 협업지능기반 로봇플러스 사업

remote_theme: rundocs/jekyll-rtd-theme

# debug:
#   compress: false
#   dist: false
#   extension: true

readme_index:
  with_frontmatter: true

sass:
  style: compress

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
